# Generated by Django 2.1.2 on 2018-10-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=1000)),
                ('progress', models.CharField(max_length=20)),
            ],
        ),
    ]
