# Generated by Django 2.1.2 on 2018-11-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
