# Generated by Django 2.1.2 on 2018-11-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0004_auto_20181109_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision.Project'),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
